### ISSUE TITLE
Questions and suggestions for TSL2591

### ISSUE THREAD

**Issue by pkomon** [Phoenix1747/Lightmeter#3]
Was a little bored at work, so looked through your Lightmeter project! ;)
I just wanted to point out a few things; but none of them is even close to relevant. Still I think, some of them are useful or at least make you consider some things you wouldn't have thought about otherwise.

So I found that the interface for interacting with the lightsensor is the class TSL2591.

- **External linkage of Adafruit obj**
In the corresponding .cpp file I instantly noticed, that you instantiate some class from an Adafruit library (apperently the library for the lightsensor you used).
https://github.com/Phoenix1747/Lightmeter/blob/05fc1ba4cb5ab443995c9a70f482ac39c41522bd/lightmeter/LIGHTSENSOR.cpp#L6
 By default, non-const variables at this scope have "**external linkage**". Linkage defines in which **translation units** a symbol (variable or function) is visible. A **translation unit** is a single .cpp file and everything (every header) it includes. A variable with "external linkage" can be referenced from all translation units! I assume, that is not what you wanted there, since it may be accessed from outside and could lead to name clashes. Also, I assume that you used this approach because you want every object of TSL2591 to refer to that single  Adafruit object (which invalidates my first guess, that is, it should be a private member). On the other hand, a variable with "internal linkage" can only be referenced within the single translation unit it was defined in. For a variable to have internal linkage, you need to use the **static** keyword. BUT there is another thing: Since this Adafruit object logically belongs to the TSL class, I suggest that you make it a private static class member - in a class, the static keyword means that the variable does not belong to a single instance of the class, but to the class itself (https://en.cppreference.com/w/cpp/language/static). Conceptually, you'd do that like this: `class x{static int a;}` in your header, `int x::a = 14;` in your source. Refer to https://en.cppreference.com/w/cpp/language/storage_duration if you want to know more about linkage.

- **Implementation of `configureSensor`**
So configureSensor is to set gain and timing. Is it on purpose, that these two cannot be set independently? I think - at the very least for code organisation - it would be beneficial to seperate these two (edit: just found out, that you indeed could use seperate operations, since you call `configureSensor` in `luxRead` with only one of two values changed). If you don't want to expose this functionality seperately, you still can make two private methods and call them in your configureSensor method. Slight optimisations: 1) since you only use [0...n] as gain- and timing- levels and map them to constants defined in the Adafruit library: you could put these constants in an array; so that array index = gain-/timing-level, no need for huge `switch`es (even tho I don't know if array access is faster than multiple comparisons, but I assume it is at least equal to `switch`'s performance) 2) you could check if `gain==-1 && timing==-1` and if so, just return - saves a few operations;

- **Implementation of `luxRead`**
In both loops you have break-conditions you could just put into while(...) instead of using seperate ifs. Also you call calculateLux twice at the end - at least return `lux` instead of calling it again. I'd just write it as `tsl.calculateLux(full, lum >> 16)`. Also the adjustment of the sensor config can be encapsulated in a seperate method (in reusable form).

Problem is, I don't have any development tools at hand right now, I couldn't  even test this stuff (with reasonable effort) - I don't trust myself well enough to just apply my suggested changes in notepad++ or smt. - I think I would just end up introducing more errors. Otherwise I would've just made a pull request and did it myself :p 

Just a few suggestions, hope I could help a little (:

**Comment by NuclearPhoenixx** [comment]
Hi, thanks for the help!

- **External linkage of Adafruit obj**

That'll be deprecated soon, I'm already working on using my own slightly modified version of the Adafruit TSL2591 lib for the lightmeter, but thanks!

- **Implementation of configureSensor**

Lol, why didn't I think of this? This makes things so much easier, thanks lol

- **Implementation of luxRead**

Holy moly, I somehow missed that I'm calling `calculateLux` and then again for the return. :man_facepalming:

I'm also looking into how to move the sensor adjustment from `calculateLux` to better methods. Don't know how to do that right now so that it's worth the effort.

Also what exactly do you mean by putting the stuff in while loops instead of seperate ifs, can you give me like an example pls?

EDIT: Implemented some changes with commit 08982ce3edd3e4e106166ad1b6e29e76d9083b8f.

**Comment by pkomon** [comment]
> That'll be deprecated soon, I'm already working on using my own slightly modified version of the Adafruit TSL2591 lib for the lightmeter, but thanks!

Cool, looking forward to looking into this too!

> Also what exactly do you mean by putting the stuff in while loops instead of seperate ifs, can you give me like an example pls?

Nevermind that; dumb mistake on my side; I meant smt. like `while(full < 62535 && gain < 3){...}` (and removing the first inner `if`) but the only thing thats good for is decreasing readability lol

Wow, you've already implemented stuff! 👍 

One more thing on the newly implemented changes (same applies to the similar line in `setGain`):
https://github.com/Phoenix1747/Lightmeter/blob/0961057931d4fd672e92daba0f6fe7ecd2a3fd88/lightmeter/LIGHTSENSOR.cpp#L76
A neat thing to do here (and in general) would be to use the size of the array instead hardcoded value (`6`). If you change the size of the array, you'd have to change that value too (yeah, I know, the array only holds pre-defined constants, so its size is unlikely to change in future BUT it's good practice and does not introduce any additional overhead whatsoever; and maaaaybe, if you want to rewrite, reuse, generalise or do whatever with this code, its safer, if you only need to change stuff at a single point - and maybe it will save you a few minutes of debugging :P). There are actually more ways of doing that, the most modern approach is using [`std::size`](https://en.cppreference.com/w/cpp/iterator/size) (added in C++17, maybe adjust your `-std` flag; don't worry, its a constexpr function, meaning that it will be evaluated at *compile time*); other ways include dividing the total array-size in bytes by the element-size in bytes (`sizeof(array)/sizeof(*array)`, C-style stuff) or using the container class [`std::array`](https://en.cppreference.com/w/cpp/container/array) (I'd even prefer this over C-style tbh).

Keep up the great work, maybe I'll get me one of those fancy lightmeters, once they are out! :)

EDIT: fixed dumb mistake

**Comment by NuclearPhoenixx** [comment]
Thanks again for the feedback! :) The only problem with using approaches such as `std::size` or `std:array` is that there are no such functions for the Arduino IDE, in other words, I cannot compile it for the MCU.

I'd have to use your C approach (`sizeof(array)/sizeof(*array)`) so I could do that and I already know I could do so, but IMHO it's not really worth the effort. I don't know how this would affect performance (I think it's evaluated at compile time tho) and I won't change the array sizes in the future since that's already all the I2C bits that the TSL2591 exposes in it's control register; also I'm a bit lazy lol.

> I meant smt. like if(full < && gain < 3){...} but the only thing thats good for is decreasing readability lol

Classic programming hack :D

> Keep up the great work, maybe I'll get me one of those fancy lightmeters, once they are out! :)

Hah! I'll let you know in 4 years ^^

**Comment by pkomon** [comment]
lol nice (:
